# REM: if you are looking for passwords or other variables
# that vary from dev to stage to prod, check the other subfolders

# setup vars
project:        "oriole-ansible"
version:        "0.1.0"
login_user:     "deploy"

# ssh vars
ssh_port: 22
# uncomment after first run (if not 22):
# ansible_ssh_port: "{{ ssh_port }}"

mode:             "deploy" # dev || deploy

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
#docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_install_compose: true 

# TODO testing-backend only has one user so just use it.
folio_user:  folio 
folio_group: "{{ folio_user }}"
okapi_user:    okapi 
okapi_group:   "{{ okapi_user }}" 

postgres_version_major:     9
postgres_version_minor:     6

# 
git_enablerepo: "ius"
git_install_from_source: false
git_packages: 
  - git2u

