---
# setup vars
environ:  "dev" # dev || test || stage || preprod || prod

# private vars
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

# apache vars:
hostname:               "{{ app_name }}-{{environ}}"
domainname:             "library.jhu.edu"

