---
# Config okapi modules
- hosts: oriole

  # todo 
  # - activeate all modules
  # - new file  add admin user for tenants 
  tasks:
    - name: get active tenents
      set_fact:
        active_tenants: "{{folio_tenants|selectattr('active')|list}}" 
      tags: indev

    - name: get active modules
      set_fact:
        active_okapi_mods: "{{okapi_modules|selectattr('active')|list}}" 
      tags: indev

    - name: check tenant okapi version 
      uri:
        url: "{{external_okapi_url}}/_/proxy/tenants/{{ item.id }}/modules/okapi-{{ okapi_version }}"
        status_code: [200,404]
      register: check_tenant_okapi
      loop: "{{ active_tenants|flatten(levels=1) }}"
      tags: indev

    - name: enable tenant okapi 
      uri:
        url: "{{external_okapi_url}}/_/proxy/tenants/{{ item.item.id }}/modules"
        method: 'POST'
        body: 
          id : "okapi-{{ okapi_version }}"
        body_format: 'json'
        status_code: [200,201]
      when: item.status != 200
      loop: "{{ check_tenant_okapi.results | flatten(levels=1) }}"
      tags: indev

    - name: enable tenant modules 
      uri:
        url: "{{external_okapi_url}}/_/proxy/tenants/{{ item.0.id }}/modules"
        method: 'POST'
        body: 
          id : "{{ item.1.name }}-{{ item.1.version }}"
        body_format: 'json'
        status_code: [200,201]
      loop: "{{ active_tenants|product(active_mods)|list }}"

    - name: check tenant admin_user
      uri:
        url: "{{external_okapi_url}}/_proxy/tenants/{{ item.id }}/users/{{item.admin_user.id}}"
        method: 'GET'
        headers:
          X-Okapi-Tenant: "{{item.id}}"
        status_code: [200,404]
      register: check_tenant_admin
      loop: "{{ active_tenants|flatten(levels=1) }}"


    - name: create tenant adminuser
      uri:
        url: "{{external_okapi_url}}/users"
        method: 'POST'
        headers:
          X-Okapi-Tenant: "{{item.item.id}}"
        body: "{{ item.item.admin_user }}"
        body_format: 'json'
        status_code: [200,201] 
      when: item.item.active != 0
      loop: "{{ check_tenant_admin.results|flatten(levels=1) }}"

    - name: reenable  mod-authtoken
      uri:
        url: "{{external_okapi_url}}/_/proxy/tenants/jh/install/{{ check_jh_authtoken[id] }}"
        method: 'post'
        body: 
          enable:
        body_format: 'json'
      when: check_jh_disable_authtoken != 200
      
      #- name: create a admin_user login
      #- name: create a admin_user permissions
      #- name: re-enable mod-authtoken
      #- name: login as adminuser
      #- name: get list of permissions
      #- name: assign permissions
     
