- name: install oriole prereqs
  hosts: okapi 

  roles:
  - { role: repo-epel, tags: ['docker'],   become: true }
  - { role: pip,       tags: ['docker'],   become: true }
  - { role: repo-ius,  tags: ['git'],      become: true }
  - { role: git,       tags: ['git'],      become: true }
  - { role: java,      tags: ['java'],     become: true }
  - { role: docker,    tags: ['docker'],   become: true }
  - { role: postgres,  tags: ['postgres'], become: true }
